### ISSUE TITLE
导入历史会话

### ISSUE THREAD

**Issue by coolcoolhua** [liunux4odoo/streamlit-chatbox#2]
chatbox.history导出的内容可以直接导入到下一次会话吗？

**Comment by liunux4odoo** [comment]
我想想，应该可以。导出格式有什么建议么？

**Comment by coolcoolhua** [comment]
> 

暂时没有。我是想用st.session_status.message = chatbox.history直接导入的，但是两者数据格式上有些差别

**Comment by coolcoolhua** [comment]
> 我想想，应该可以。导出格式有什么建议么？

暂时没有。只要是能直接用上数据就行，最好导入记录时还能保持之前的markdown形式

**Comment by liunux4odoo** [comment]
1.1.7版已经上传。可以将历史消息导出为json文件，然后可以从json文件再导入到对话历史。
