### ISSUE TITLE
st.session_state keyerror chat_history

### ISSUE THREAD

**Issue by alexxchen** [liunux4odoo/streamlit-chatbox#5]
运行中随机出现报错。不明白为什么明明在chat_box.init_session()里已经重新设置了session_state,但是却还是空字典{}。而且网络越差，出现的概率越高，当然localhost也会出现。有没有什么好的解决办法。

**Comment by liunux4odoo** [comment]
我的经验是，如果短期内同一个控制台短期内多次启动/停止服务，有概率导致session_state丢失，一般关掉重开一个控制台就可以解决。没有稳定复现的方法，所以无法定位错误

**Comment by alexxchen** [comment]
@liunux4odoo 试了下确实可以。还有一个问题请教一下大神，如果网络不稳定，webui会发送多次一样的请求，有办法避免吗？

**Comment by liunux4odoo** [comment]
> @liunux4odoo 试了下确实可以。还有一个问题请教一下大神，如果网络不稳定，webui会发送多次一样的请求，有办法避免吗？

这个不太有办法，streamlit前后端通信的机制决定了这种情况没办法。最多自己在后端判断短期内收到重复的数据就丢掉。

**Comment by H9990HH969** [comment]
这个在我电脑上是100%复现，只要是第二次提问，必定会出现这个问题，就是在和大模型通信后，要显示在chatbox上这个时候，一定会出现key error
