### ISSUE TITLE
咨询chatchat项目

### ISSUE THREAD

**Issue by zhang2645795251** [liunux4odoo/streamlit-chatbox#9]
你好，大佬，我看chatchat项目下的agent功能是您开发的，我想咨询一些问题，您看可以吗，有偿

**Comment by liunux4odoo** [comment]
你可以把你的问题私信发给我，能解决的我会告诉你。

**Comment by zhang2645795251** [comment]
非常感谢你的帮助目前我使用的0.20版本，模型是chatglm3，在调用其中的




张文海
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liunux4odoo/streamlit-chatbox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月29日(星期一) 晚上8:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liunux4odoo/streamlit-chatbox] 咨询chatchat项目 (Issue #9)





 
你可以把你的问题私信发给我，能解决的我会告诉你。

**Comment by liunux4odoo** [comment]
0.2.x的agent功能只是试验性的，而且很久没有维护了。后来glm3的function call做了改进，其代码已经不适配了。0.3.x版本提供了更好的glm3/qwen agent支持，可以用dev分支提前体验。

**Comment by zhang2645795251** [comment]
今天简单配置了环境运行dev，不过有些问题
请问有配置文档之类的吗。谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月30日(周二) 上午7:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liunux4odoo/streamlit-chatbox] 咨询chatchat项目 (Issue #9)




 
0.2.x的agent功能只是试验性的，而且很久没有维护了。后来glm3的function call做了改进，其代码已经不适配了。0.3.x版本提供了更好的glm3/qwen agent支持，可以用dev分支提前体验。
